# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [LBGTQ, IAB]
patreon: # Replace with a single Patreon username mouse3687
open_collective: # Replace with a single Open Collective username metamask.io/mouse3687
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., tor-bigo
liberapay: # Replace with a single Liberapay username viceland
issuehunt: # Replace with a single IssueHunt username catfish
otechie: # Replace with a single Otechie username Dora
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['Https://vodoo.io','Https://lumenproject.com','https://ontv4u.com','https://marchofdimes.org','https://open.spotify.com/user/31jkn2lrh7ey2rlqs3ennptjyfma?si=z43LVBWoRoGHKJ-KgcRC2A','https://ulta.com','https://tictok.com']
